apiVersion: tenancy.x-k8s.io/v1alpha1
kind: ClusterVersion
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: cv-sample-np
spec:
  # a statefulset and service bundle for etcd
  etcd:
    metadata:
      name: etcd 
    statefulset:
      metadata:
        name: etcd
      spec:
        hostNetwork: true
        replicas: 1
        revisionHistoryLimit: 10
        serviceName: etcd
        selector:
          matchLabels:
            component-name: etcd
        # etcd will not be updated, unless it is deleted
        updateStrategy:
          type: OnDelete
        template:
          metadata:
            labels:
              component-name: etcd
          spec:
            subdomain: etcd
            containers:
            - name: etcd
              image: virtualcluster/etcd-v3.4.0
              imagePullPolicy: Always
              command: 
              - etcd
              # pass the pod name(hostname) to container for composing the advertise-urls args
              env:
              - name: HOSTNAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name 
              args:
              - --name=$(HOSTNAME)
              - --trusted-ca-file=/etc/kubernetes/pki/root/tls.crt
              - --client-cert-auth 
              - --cert-file=/etc/kubernetes/pki/etcd/tls.crt
              - --key-file=/etc/kubernetes/pki/etcd/tls.key
              - --peer-client-cert-auth 
              - --peer-trusted-ca-file=/etc/kubernetes/pki/root/tls.crt
              - --peer-cert-file=/etc/kubernetes/pki/etcd/tls.crt
              - --peer-key-file=/etc/kubernetes/pki/etcd/tls.key
              - --initial-cluster-state=new
              - --initial-cluster-token=vc-etcd
              - --data-dir=/var/lib/etcd/data
              volumeMounts:
              - mountPath: /etc/kubernetes/pki/etcd
                name: etcd-ca
                readOnly: true
              - mountPath: /etc/kubernetes/pki/root
                name: root-ca
                readOnly: true
            volumes: 
            - name: etcd-ca
              secret:
                defaultMode: 420
                secretName: etcd-ca
            - name: root-ca
              secret:
                defaultMode: 420
                secretName: root-ca
    # etcd will be accessed only by apiserver from inside the cluster, so we use a headless service to 
    # encapsulate it
    service:
      metadata:
        name: etcd
        annotations:
          service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
      spec:
        type: ClusterIP
        clusterIP: None
        selector:
          component-name: etcd
  # a statefulset and service bundle for apiserver
  apiServer:
    metadata:
      name: apiserver
    statefulset:
      metadata:
        name: apiserver
      spec:
        hostNetwork: true
        replicas: 1
        revisionHistoryLimit: 10
        serviceName: apiserver-svc
        selector:
          matchLabels:
            component-name: apiserver
        # apiserver will not be updated, unless it is deleted
        updateStrategy:
          type: OnDelete
        template:
          metadata:
            labels:
              component-name: apiserver
          spec:
            hostname: apiserver
            subdomain: apiserver-svc
            containers:
            - name: apiserver
              image: virtualcluster/apiserver-v1.15.4
              imagePullPolicy: Always
              command:
              - kube-apiserver
              args:
              - --bind-address=0.0.0.0
              - --allow-privileged=true
              - --anonymous-auth=true
              - --client-ca-file=/etc/kubernetes/pki/root/tls.crt
              - --tls-cert-file=/etc/kubernetes/pki/apiserver/tls.crt
              - --tls-private-key-file=/etc/kubernetes/pki/apiserver/tls.key
              - --kubelet-https=true
              - --kubelet-client-certificate=/etc/kubernetes/pki/apiserver/tls.crt
              - --kubelet-client-key=/etc/kubernetes/pki/apiserver/tls.key
              - --enable-bootstrap-token-auth=true
              - --etcd-cafile=/etc/kubernetes/pki/root/tls.crt
              - --etcd-certfile=/etc/kubernetes/pki/apiserver/tls.crt
              - --etcd-keyfile=/etc/kubernetes/pki/apiserver/tls.key
              - --service-account-key-file=/etc/kubernetes/pki/service-account/tls.key
              - --service-cluster-ip-range=10.32.0.0/16
              - --service-node-port-range=30000-32767
              - --authorization-mode=Node,RBAC
              - --runtime-config=api/all
              - --enable-admission-plugins=NamespaceLifecycle,NodeRestriction,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota
              - --apiserver-count=1
              - --endpoint-reconciler-type=master-count
              - --v=2
              volumeMounts:
              - mountPath: /etc/kubernetes/pki/apiserver
                name: apiserver-ca
                readOnly: true
              - mountPath: /etc/kubernetes/pki/root
                name: root-ca
                readOnly: true
              - mountPath: /etc/kubernetes/pki/service-account
                name: serviceaccount-rsa
                readOnly: true
            terminationGracePeriodSeconds: 30
            dnsConfig:
              searches:
              - cluster.local
            volumes:
            - name: apiserver-ca
              secret:
                defaultMode: 420
                secretName: apiserver-ca
            - name: root-ca
              secret:
                defaultMode: 420
                secretName: root-ca
            - name: serviceaccount-rsa
              secret:
                defaultMode: 420
                secretName: serviceaccount-rsa
    service:
      metadata:
        name: apiserver-svc
      spec:
        type: ClusterIP
        clusterIP: None
        selector:
          component-name: apiserver
  # a statefulset and service bundle for controller-manager
  controllerManager:
    metadata:
      name: controller-manager
    # statefuleset template for controller-manager
    statefulset:  
      metadata:
        name: controller-manager
      spec:
        hostNetwork: true
        serviceName: controller-manager-svc
        replicas: 1
        selector:
          matchLabels:
            component-name: controller-manager
        updateStrategy:
          type: OnDelete
        template:
          metadata:
            labels:
              component-name: controller-manager
          spec:
            containers:
            - name: controller-manager
              image: virtualcluster/controller-manager-v1.15.4
              imagePullPolicy: Always
              command:
              - kube-controller-manager
              args:
              - --bind-address=0.0.0.0
              - --cluster-cidr=10.200.0.0/16
              - --cluster-signing-cert-file=/etc/kubernetes/pki/root/tls.crt
              - --cluster-signing-key-file=/etc/kubernetes/pki/root/tls.key
              - --kubeconfig=/etc/kubernetes/kubeconfig/controller-manager-kubeconfig
              - --authorization-kubeconfig=/etc/kubernetes/kubeconfig/controller-manager-kubeconfig
              - --authentication-kubeconfig=/etc/kubernetes/kubeconfig/controller-manager-kubeconfig
              - --leader-elect=false
              - --root-ca-file=/etc/kubernetes/pki/root/tls.crt
              - --service-account-private-key-file=/etc/kubernetes/pki/service-account/tls.key
              - --service-cluster-ip-range=10.32.0.0/24
              - --use-service-account-credentials=true
              - --experimental-cluster-signing-duration=87600h
              - --node-monitor-grace-period=200s
              - --v=2
              volumeMounts:
              - mountPath: /etc/kubernetes/pki/root
                name: root-ca
                readOnly: true
              - mountPath: /etc/kubernetes/pki/service-account
                name: serviceaccount-rsa
                readOnly: true
              - mountPath: /etc/kubernetes/kubeconfig
                name: kubeconfig
                readOnly: true
            volumes:
            - name: root-ca
              secret:
                defaultMode: 420
                secretName: root-ca
            - name: serviceaccount-rsa 
              secret:
                defaultMode: 420
                secretName: serviceaccount-rsa
            - name: kubeconfig
              secret:
                defaultMode: 420
                secretName: controller-manager-kubeconfig
    # controller-manager will never be accessed proactively, no need to be exposed 
